FROM registry.access.redhat.com/rhscl/postgresql-96-rhel7
 
ENV SUMMARY="Postgresql 9.6 with ..." \
    DESCRIPTION="Postgresql 9.6 ..."
 
LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION"
 
# NOTES:
RUN 

USER 1001
